tasks:
- command: 'brew tap heroku/brew && brew install heroku &&
  echo Brew Heroku installation finished &&
  echo Updating heroku executable code... &&
  herpath=$(readlink -f `which heroku`) &&
  sed -i ''s/\"\$NODE\"\ \"/node\ \"/'' $herpath &&
  echo Done &&
  echo Settings aliases... &&
  source scripts/setaliases &&
  echo Done'