#!/usr/bin/bash

alias 'm=python3 manage.py'
alias 'dja=django-admin'
alias 'run=m runserver'
alias 'cstatic=m collectstatic --no-input | tail -n 1'
alias 'push=git push && heroku login -i && git push heroku master'